spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# 🔥 IMPORTANTE (troca isso)
spring.jpa.hibernate.ddl-auto=none

server.port=${PORT:8080}

app.upload-dir=uploads

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# 🔥 força rodar schema.sql + data.sql
spring.sql.init.mode=always
spring.sql.init.platform=postgres

# 🔥 garante ordem correta
spring.jpa.defer-datasource-initialization=true
