spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# 🔥 deixa NONE por enquanto pra não conflitar com schema.sql
spring.jpa.hibernate.ddl-auto=none

server.port=${PORT:8080}

app.upload-dir=uploads

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# 🔥 roda apenas o schema (cria tabelas)
spring.sql.init.mode=always
spring.sql.init.platform=postgres
spring.sql.init.schema-locations=classpath:schema.sql

# ❌ DESATIVADO (pra não crashar)
# spring.sql.init.data-locations=classpath:data.sql

spring.jpa.defer-datasource-initialization=true
